name = "cf-emby-proxy-ui"
main = "worker.js"
compatibility_date = "2024-03-12"

# === 绑定 KV ===
[[kv_namespaces]]
binding = "KV" 
id = "REPLACE_ME_KV_ID" 

# === 绑定 D1 数据库 ===
[[d1_databases]]
binding = "DB" 
database_name = "REPLACE_ME_D1_NAME" 
database_id = "REPLACE_ME_D1_ID"